---
title: "Reproducible Reporting"
author: "Yourname"
date: "17.11.2014"
output: html_document
---

## Markdown Syntax

### Lists

1. Element one
2. Element two
3. Element three
4. Elemnt four

* One
* Two
    + Two one
    + Two two
        - Two two one
* Three
    1. Three one
    2. Three two
    
    
> 42 is the answer to the meaning of life,  
> the universe, and everything.  
> – *Douglas Adams*


| Left align | Right align | Center align |
|:-----------|------------:|:------------:|
| This       |        This |     This     |
| column     |      column |    column    |
| left       |       right |    center    |


---- task plot

### Plots

```{r preparation, include = F}
require(ggplot2)
```

```{r fig.align = 'center', fig.width = 6, fig.height = 4, echo = F}
qplot(mpg, wt, data = mtcars, colour = cyl)
```

--- task kable 

```{r preparation, include = F}
subset_of_mtcars = head(mtcars, 7)
```

```{r themagictable, results = 'asis'}
kable(subset_of_mtcars, format = "markdown", digits = 1)
```
