---
title: "Reproducible Reporting"
author: "Yourname"
date: "17.11.2014"
output: html_document
---

## Exercises

### Lists

1. Element one
2. *Element* two
3. Element **three**
4. Elemnt four

* One
* Two
    + Two ***one***
    + Two two
        - Two two one
* Three
    1. Three one
    2. Three two
    

### Tables            

| First | Second | Third | Fourth | Fifth |
|:-----:|--------|-------|--------|------:|
|   1   | 2      | 3     | 4      |     5 |
|   5   | 4      | 3     | 2      |     1 |
|   1   | 2      | 3     | 4      |     5 |

### Plots

```{r preparation_packages, include = F}
if("ggplot2" %in% rownames(installed.packages()) == FALSE) install.packages("ggplot2") else require(ggplot2)
if("knitr" %in% rownames(installed.packages()) == FALSE) install.packages("knitr") else require(knitr)
```

```{r fig.align = 'center', fig.width = 6, fig.height = 4, echo = F}
qplot(mpg, wt, data=mtcars, colour=cyl)
```

### Automagical Tables

```{r preparation_subset, include = F}
subset_of_mtcars = head(mtcars, 7)
```

```{r themagictable, results = 'asis'}
kable(subset_of_mtcars, format = "markdown", digits = 1)
```